# Generated by Django 5.1.7 on 2025-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplace',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('freezer', 'Freezer'), ('drawer', 'Drawer'), ('box', 'Box')], default='room', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
