# Generated by Django 5.1.7 on 2025-03-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storageplace_type_alter_storageplace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplace',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.storageplace'),
        ),
    ]
