# Generated by Django 5.1.7 on 2025-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storageplace_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrsample',
            name='not_found',
            field=models.BooleanField(default=False),
        ),
    ]
