# Generated by Django 5.1.7 on 2025-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pcrsample_not_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrsample',
            name='active_use',
            field=models.BooleanField(default=False),
        ),
    ]
