# Generated by Django 5.1.7 on 2025-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pcrsample_active_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrsample',
            name='negative_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcrsample',
            name='positive_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
