# Generated by Django 5.1.7 on 2026-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pcrsample_negative_for_pcrsample_positive_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='active_use_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='not_found',
            field=models.BooleanField(default=False),
        ),
    ]
