# Generated by Django 5.1.7 on 2026-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usagelog_active_use_date_usagelog_not_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrsample',
            name='volume_unit',
            field=models.CharField(choices=[('uL', 'Microliters (µL)'), ('mL', 'Milliliters (mL)'), ('L', 'Liters (L)')], default='mL', max_length=2),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='volume_unit',
            field=models.CharField(choices=[('uL', 'Microliters (µL)'), ('mL', 'Milliliters (mL)'), ('L', 'Liters (L)')], default='mL', max_length=2),
        ),
        migrations.AlterField(
            model_name='pcrsample',
            name='sample_volume',
            field=models.FloatField(help_text='Initial sample volume'),
        ),
        migrations.AlterField(
            model_name='pcrsample',
            name='sample_volume_remaining',
            field=models.FloatField(help_text='Remaining sample volume'),
        ),
    ]
