# Generated by Django 5.1.7 on 2026-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pcrsample_volume_unit_usagelog_volume_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycler',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='extractor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pcrkit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sampletype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storageplace',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['name']},
        ),
    ]
